// CODE GENERATED BY mumbojumbo 1.1 (https://github.com/jeromer/mumbojumbo) DO NOT EDIT !!!!

package sha256

import (
	"unsafe"
)

func eax() uint8 {
	return uint8(unsafe.Sizeof(true))
}

func Get() string {
	return string(
		[]byte{
			((eax()<<eax()|eax())<<eax()<<eax()<<eax()<<eax()<<eax() ^ eax()),
			(((eax()<<eax()|eax())<<eax()^eax())<<eax()<<eax()<<eax() ^ eax()) << eax(),
		},
	)
}
